### ISSUE TITLE
MSAL Failure

### ISSUE THREAD

**Issue by larso077** [microsoftgraph/ios-swift-snippets-sample#15]
Device: IPhone 7 Plus
iOS 13.1
Xcode 11
Log:
Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=2 "Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start." UserInfo={NSDebugDescription=Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start.}
Failed with internal MSAL error  Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Failed to start an interactive session, MSALInternalErrorCodeKey=-50000, MSALCorrelationIDKey=18F986A3-1E8F-4496-B361-DA226475AEB9}
Error:  Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Failed to start an interactive session, MSALInternalErrorCodeKey=-50000, MSALCorrelationIDKey=18F986A3-1E8F-4496-B361-DA226475AEB9}

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-ios-swift for a Swift sample.
