### ISSUE TITLE
Upload large files to one drive swift

### ISSUE THREAD

**Issue by sreejithsree123** [microsoftgraph/ios-swift-snippets-sample#9]
i just want to upload large file now it take only less than 10 mb size files to upload. createUploadSession need to add for uploading large files. I couldn't find the right solution and for showing the progressBar. If you give the sample for that it will be great help.

**Comment by JohnMAustin78** [comment]
Good idea. I'll add that to my work backlog.

John

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-ios-swift for a Swift sample.
